# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64cc603216597693ae29631c3d0866131dbbb5e4e713772380a19f4334db40eb91e29a69efbe744556dcab886c0961b297b2b57ec088bda6ee4ef20758f1ff29

test:
  secret_key_base: 644cc8c7584476067ea046795bfbc88e6f7929aafe41a54f0561bcc963c5eb4409d17d33230c547736a48b23912559f784fdca9959a4df89779cf8d53fcc92e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
